<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_User Notes</name>
   <tag></tag>
   <elementGuidId>b872c83f-5dda-457e-acd9-aab7ff821341</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tovuti_nav_user_notes']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>04ec1071-e632-42de-9cd4-aff2bc29b2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_users&amp;view=notes</value>
      <webElementGuid>0ce90d48-24ff-425b-8fbb-acce425fed6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>3f8a22b3-3a01-4cfd-8063-353c9730f51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>1bc8283c-9494-4b99-b509-3e99e8912f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        User Notes                                                                                                                    </value>
      <webElementGuid>c4f4803d-faf0-4cea-93cc-9d62b7fd1916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tovuti_nav_user_notes&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>6a8bed75-d710-4092-91c2-0cea119f4feb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tovuti_nav_user_notes']/a</value>
      <webElementGuid>2c86654f-cc56-4ff3-8f3b-7d2168402afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'User Notes')]</value>
      <webElementGuid>1a841d30-a906-4acd-b5d7-774ad3ea57cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Importer'])[1]/following::a[1]</value>
      <webElementGuid>c5a08f0b-2185-407e-950b-3e24678f605c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Teams'])[1]/following::a[2]</value>
      <webElementGuid>21a0df2d-46c9-4f92-9aed-03d0133f1fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Note Categories'])[1]/preceding::a[1]</value>
      <webElementGuid>4e9afd64-2864-4c24-bc5d-14c2129fd91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access Levels'])[1]/preceding::a[2]</value>
      <webElementGuid>dc29c70a-874a-45b4-8778-cfc21fa078bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Notes']/parent::*</value>
      <webElementGuid>7b57cd8f-3573-40a2-b120-13e4b232d042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?option=com_users&amp;view=notes')]</value>
      <webElementGuid>48fbb4f0-1899-4c0e-ae11-c690bc82adb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/ul/li[6]/a</value>
      <webElementGuid>075a5b23-04f4-4a56-9209-4885ba3320aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_users&amp;view=notes' and (text() = '
                                        User Notes                                                                                                                    ' or . = '
                                        User Notes                                                                                                                    ')]</value>
      <webElementGuid>6d292bd6-9deb-4c0c-8f57-47784696669c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
