<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Workday Connect_icon-search text-muted</name>
   <tag></tag>
   <elementGuidId>62586e62-ce48-470b-afd3-373803ba641d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='filter-bar']/div/div/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-search.text-muted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ea620aea-e49a-4bd4-9afe-7a34c05feab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-search text-muted</value>
      <webElementGuid>4d4d4004-8c99-4bb9-9953-1c4b65c8c354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-bar&quot;)/div[@class=&quot;float-start me-2&quot;]/div[@class=&quot;input-group&quot;]/button[@class=&quot;btn border&quot;]/i[@class=&quot;icon-search text-muted&quot;]</value>
      <webElementGuid>558825cc-f0a7-484c-995c-a6b81802b3af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-bar']/div/div/button/i</value>
      <webElementGuid>26fec9f7-92fb-42f4-aec3-2822c976193a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button/i</value>
      <webElementGuid>aaa797f9-db29-48a4-b2d5-fedb68395b3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
