<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ID_k-icon k-clear-value k-i-close</name>
   <tag></tag>
   <elementGuidId>23b83bf1-1141-4812-89dd-9bd5389919b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-icon.k-clear-value.k-i-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='j-main-container']/div/div/div/table/thead/tr[2]/th[4]/span/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>54316f6a-6a99-41dc-a757-0145d7f76147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>aeeecc3f-3bbd-4ad3-b0cc-ba30db953a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-clear-value k-i-close</value>
      <webElementGuid>ba31d5fd-d859-459d-8c4c-19f82b382598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>clear</value>
      <webElementGuid>087da1da-6e21-422d-bbc3-e175fa4652b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87c989e2-c067-4d79-bf96-b13d7c3b9839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c50dd604-816d-4217-b82e-1807c1c13ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j-main-container&quot;)/div[@class=&quot;k-grid k-widget&quot;]/div[@class=&quot;k-grid-header&quot;]/div[@class=&quot;k-grid-header-wrap k-auto-scrollable&quot;]/table[1]/thead[1]/tr[@class=&quot;k-filter-row&quot;]/th[4]/span[@class=&quot;k-filtercell&quot;]/span[@class=&quot;k-operator-hidden&quot;]/span[@class=&quot;k-widget k-autocomplete k-header k-state-default k-state-focused k-state-hover&quot;]/span[@class=&quot;k-icon k-clear-value k-i-close&quot;]</value>
      <webElementGuid>13d9e03d-2afa-4696-951e-589230ba56ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='j-main-container']/div/div/div/table/thead/tr[2]/th[4]/span/span/span/span</value>
      <webElementGuid>27908e89-8f3e-4b00-8795-1fb9e2cea269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>545c25db-1c3a-4bad-a33a-22b59afa97bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'clear']</value>
      <webElementGuid>64812d1e-d578-4122-82cc-1d1d600f7ec6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
