<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Instructions_fas fa-analytics</name>
   <tag></tag>
   <elementGuidId>75accb37-1b20-4df7-beac-1870a59c61db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menuItem-tovuti_nav_analytics']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-analytics</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2d21a021-4ea0-4ac2-9b38-5ec072ef1563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-analytics</value>
      <webElementGuid>00fb27e4-ff9c-4db5-ac00-76a5ee994eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuItem-tovuti_nav_analytics&quot;)/a[@class=&quot;nav-link&quot;]/i[@class=&quot;fas fa-analytics&quot;]</value>
      <webElementGuid>be5616e7-30f7-4761-8488-7ab2d8205872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menuItem-tovuti_nav_analytics']/a/i</value>
      <webElementGuid>f7ff34a1-5199-4f9d-8810-7c16bc8d8a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/i</value>
      <webElementGuid>5c957f16-14aa-437b-be68-70152318b20c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
