<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Instructions_fas fa-comment-alt</name>
   <tag></tag>
   <elementGuidId>b891453e-3af3-46ed-a2b6-f2fd3bb0eab8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menuItem-tovuti_nav_social']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-comment-alt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>474a7eb7-bfed-49e5-85a8-625c04c38db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-comment-alt</value>
      <webElementGuid>a086658b-eb34-428f-be50-73baa79fe84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuItem-tovuti_nav_social&quot;)/a[@class=&quot;nav-link&quot;]/i[@class=&quot;fas fa-comment-alt&quot;]</value>
      <webElementGuid>b90afe8a-dc33-45ac-9e3a-1035d903e387</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menuItem-tovuti_nav_social']/a/i</value>
      <webElementGuid>20e66aeb-37e4-4b41-9723-a82093340ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/i</value>
      <webElementGuid>c93e6b7c-9675-4310-8b7a-8efdc4a364cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
