<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Interactive Content</name>
   <tag></tag>
   <elementGuidId>f48dd0ca-642d-40b6-8276-fb6f3e3accbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tovuti_nav_interactive_content']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7035ef9a-7db0-42b5-bb25-93281bba0b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_interactivecontent</value>
      <webElementGuid>3153102f-3e4b-494d-bf9c-2f4ee68e54cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>720ca0aa-ea7b-4778-b5ba-6c00761731b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>84b6ac97-a6f1-4ad7-9bf2-7b0922cce4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Interactive Content                                                                                                                    </value>
      <webElementGuid>c5c3187e-c57d-4d38-863e-36c06917904d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tovuti_nav_interactive_content&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>f3312bf4-3863-4b10-8b93-28f0165a1b92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tovuti_nav_interactive_content']/a</value>
      <webElementGuid>f596ad76-a9ec-4b4f-b7b8-cfd8a1a4ecda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Interactive Content')]</value>
      <webElementGuid>cae87d43-bfa2-4af8-b8e7-966a333148af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instructors'])[1]/following::a[1]</value>
      <webElementGuid>9eb3242f-daef-4676-8f0b-0823fdb04d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eLearning Packages'])[1]/preceding::a[1]</value>
      <webElementGuid>9e74344b-1dbb-4bb7-8b00-259312780ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assessments'])[1]/preceding::a[2]</value>
      <webElementGuid>cbec7c7f-8c45-4b9a-ae35-46a65049058b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Interactive Content']/parent::*</value>
      <webElementGuid>39e05ac2-5c8e-4272-b246-1606fc67c1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'index.php?option=com_interactivecontent')])[2]</value>
      <webElementGuid>6a52ec99-533a-4076-8065-1032a291f3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div[2]/ul/li/a</value>
      <webElementGuid>a5e05747-68c2-4868-b128-85da773244be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_interactivecontent' and (text() = '
                                        Interactive Content                                                                                                                    ' or . = '
                                        Interactive Content                                                                                                                    ')]</value>
      <webElementGuid>6235576f-3313-4a1e-a2b9-a09cef27e567</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
