<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Registered</name>
   <tag></tag>
   <elementGuidId>0828404e-ef44-4604-8655-b5e35680c4f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='groupList']/tbody/tr/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>856d6602-85e6-4171-a5af-c73e6ed4cb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/administrator/index.php?option=com_users&amp;task=group.edit&amp;id=2</value>
      <webElementGuid>721ed125-416f-4934-99c6-2db81bb6172e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								Registered</value>
      <webElementGuid>ca73819f-de1e-46ea-8796-33e85f4f7871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;groupList&quot;)/tbody[1]/tr[@class=&quot;row0&quot;]/td[2]/a[1]</value>
      <webElementGuid>648a0912-1249-462c-ac20-7ce292020859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='groupList']/tbody/tr/td[2]/a</value>
      <webElementGuid>8ccd17be-30ac-4ab8-bce3-da96d2a92127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Registered')]</value>
      <webElementGuid>b1ee9be9-38e9-4213-ade6-129f78308d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disabled Users'])[1]/following::a[2]</value>
      <webElementGuid>234fd480-1cb1-47e3-9f05-32b7c95acbe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'groupList', '&quot;', ')/tbody[1]/tr[@class=', '&quot;', 'row0', '&quot;', ']/td[2]/a[1]')])[1]/preceding::a[3]</value>
      <webElementGuid>4a6c9c1b-a384-4734-869b-7ec286e765b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Registered']/parent::*</value>
      <webElementGuid>bf78aa4a-aaeb-4d46-a979-3bec1e019994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/administrator/index.php?option=com_users&amp;task=group.edit&amp;id=2')]</value>
      <webElementGuid>cc1636dd-d18a-45b3-a608-4b6531102248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>875cd15c-3c88-44fe-94ef-7665f141904a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/administrator/index.php?option=com_users&amp;task=group.edit&amp;id=2' and (text() = '
								Registered' or . = '
								Registered')]</value>
      <webElementGuid>43f875f9-fc27-4137-9490-19e95ccfb9c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
