<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_filtersearch</name>
   <tag></tag>
   <elementGuidId>ee6e6a10-d059-438f-a043-c3508f0342d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69cc0573-5675-4356-84ca-70c7994a4bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>231f1655-539d-4898-84dc-64938a71c1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter[search]</value>
      <webElementGuid>9f0f14a1-c85b-42bc-bcdc-c7d9ac23d16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter_search</value>
      <webElementGuid>db6edab5-b847-4dc6-ba4f-7ef06ad55d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>5afc56e9-5baf-48ab-b537-cf0ae7192063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip211025</value>
      <webElementGuid>bdb09583-7683-45d8-ab75-955c05afb273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter_search&quot;)</value>
      <webElementGuid>568b8ff1-9876-4337-9ad9-fc12be7a9ad1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter_search']</value>
      <webElementGuid>750f8d6b-5bb3-4115-85dc-6a0a6156a5c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='j-main-container']/div/div/div/div/div/input</value>
      <webElementGuid>bb27cdc5-90af-4982-8136-99830ca85c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>33eddcf8-c33e-4779-99bc-e3782ff99235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'filter[search]' and @id = 'filter_search' and @placeholder = 'Search']</value>
      <webElementGuid>d7db7c09-e2bf-4f9b-8799-f7840986c329</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
