<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search_icon-search</name>
   <tag></tag>
   <elementGuidId>e886799a-0927-47b5-ac75-734547aaaaa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.icon-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='j-main-container']/div/div/div/div/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef4823e1-4007-4b1a-ab59-51b38c67e7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-search</value>
      <webElementGuid>1624d03d-8cf2-4a9f-8fe0-973f4b46653f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j-main-container&quot;)/div[@class=&quot;js-stools clearfix&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;js-stools-container-bar&quot;]/div[@class=&quot;float-start&quot;]/div[@class=&quot;input-group&quot;]/button[@class=&quot;btn border&quot;]/span[@class=&quot;icon-search&quot;]</value>
      <webElementGuid>ed71ac82-5163-4645-a6fb-47080c7f8d5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='j-main-container']/div/div/div/div/div/button/span</value>
      <webElementGuid>44a825db-d9cd-4ec0-a966-38badeb7d419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/button/span</value>
      <webElementGuid>39f62bb5-9adc-4d81-ae72-784b650e8f87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
