<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Contains_k-select</name>
   <tag></tag>
   <elementGuidId>8831fec5-e076-4308-8dbf-5f1a6e5aab93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='grid']/div[3]/div/table/thead/tr[2]/th[2]/span/span/span[2]/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b8e439df-cc61-4f1a-ae5b-44c42fe867d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>851b56fd-77d9-45ac-b4b9-477d01afb569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-select</value>
      <webElementGuid>bec93adc-80ad-4e42-b1c5-78cbba655b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6b3aa85e-5adc-48cd-8b98-b47dc330f597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid&quot;)/div[@class=&quot;k-grid-header&quot;]/div[@class=&quot;k-grid-header-wrap k-auto-scrollable&quot;]/table[1]/thead[1]/tr[@class=&quot;k-filter-row&quot;]/th[2]/span[@class=&quot;k-filtercell&quot;]/span[1]/span[@class=&quot;k-widget k-dropdown k-header k-dropdown-operator&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-hover k-state-focused&quot;]/span[@class=&quot;k-select&quot;]</value>
      <webElementGuid>4901d138-cf68-41fc-975d-6e454b3ddf20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid']/div[3]/div/table/thead/tr[2]/th[2]/span/span/span[2]/span/span[2]</value>
      <webElementGuid>3a7b478b-30c0-4c7f-a9af-8621aa0864a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contains'])[1]/following::span[1]</value>
      <webElementGuid>84f7a6fa-8688-4e1c-b2d2-3ea57d9e54e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::span[16]</value>
      <webElementGuid>3c038566-0aa8-40a7-bf2a-f67383b7aebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contains'])[2]/preceding::span[6]</value>
      <webElementGuid>df6692d7-8c5f-4f5b-a18f-3fbc1a2d529e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contains'])[3]/preceding::span[17]</value>
      <webElementGuid>f833e084-d6c5-4570-b8b5-749644bcb9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span[2]</value>
      <webElementGuid>efdef418-0ee2-4217-8aa0-6fbe99f5ed14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
