<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_User Teams</name>
   <tag></tag>
   <elementGuidId>65f71764-4b96-4503-bab0-ee63d2d26a72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tovuti_nav_user_teams']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f2e3c01c-a2a1-4a89-a72d-c6480ca2983a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_axs&amp;view=teams</value>
      <webElementGuid>07847e09-4a96-4017-9e9f-cd0dac66ee1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>88ff3537-a8da-471c-8c34-79623efcf6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>31214426-dd8c-4dac-9028-d9703190af15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        User Teams                                                                                                                    </value>
      <webElementGuid>87c0520d-3e29-4fa4-b67b-8b65d13e0777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tovuti_nav_user_teams&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>b32463f6-4622-4fd1-b6ca-50261132f8db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tovuti_nav_user_teams']/a</value>
      <webElementGuid>01bcf612-e2ae-4882-9dd5-ed92704fb368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'User Teams')]</value>
      <webElementGuid>1cb7fbd9-1832-42ad-bb78-0c6ec470bcb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Groups'])[1]/following::a[1]</value>
      <webElementGuid>9ac3ccb7-e079-4aec-abfd-b6d0b028e7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Profile Fields'])[1]/following::a[2]</value>
      <webElementGuid>32808f87-e463-4e7f-b873-a22a84f45a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Importer'])[1]/preceding::a[1]</value>
      <webElementGuid>29ba06d0-7ad9-42b8-a168-5df5a4a69ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Notes'])[1]/preceding::a[2]</value>
      <webElementGuid>a09cb28f-3cea-495f-a732-a67ce08cc59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Teams']/parent::*</value>
      <webElementGuid>6366c9de-f815-4646-b6f2-afa89f5e4ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?option=com_axs&amp;view=teams')]</value>
      <webElementGuid>3e29af42-b114-4d3a-8dea-1cb08daaed71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li[4]/a</value>
      <webElementGuid>f37fe7dc-a833-44b5-8457-60c8e3d40111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_axs&amp;view=teams' and (text() = '
                                        User Teams                                                                                                                    ' or . = '
                                        User Teams                                                                                                                    ')]</value>
      <webElementGuid>d84c6f20-12a8-4fa9-bed5-3dd00eee3886</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
