<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Instructions_fas fa-users</name>
   <tag></tag>
   <elementGuidId>34d24d4d-d07d-493b-a1cf-2991fe145174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menuItem-tovuti_nav_people']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-users</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>24e51096-1fb3-441f-8499-e0142b2f8608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-users</value>
      <webElementGuid>87764c98-1c42-4ad1-8245-17fa33eb9782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuItem-tovuti_nav_people&quot;)/a[@class=&quot;nav-link&quot;]/i[@class=&quot;fas fa-users&quot;]</value>
      <webElementGuid>58dd94b5-c07f-45a7-bd4f-28678215f183</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menuItem-tovuti_nav_people']/a/i</value>
      <webElementGuid>5d86f720-74fe-4c50-8101-226d5ac48a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a/i</value>
      <webElementGuid>f07358d1-b5c6-4215-ba60-87b883b1881d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
