<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_User Groups</name>
   <tag></tag>
   <elementGuidId>fdf3569c-d0f2-419e-8559-3fa72c47d468</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tovuti_nav_user_groups']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f025c221-b977-4a62-ac84-3aef5ca02cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_users&amp;view=groups</value>
      <webElementGuid>c5d849a4-1775-41f6-85a3-e4a4bed4fa7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>35c8a421-3d31-49e9-bc18-283db8bc61cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>a443cd00-b73d-499a-818e-ff8d003cb3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        User Groups                                                                                                                    </value>
      <webElementGuid>50660b05-7aed-4177-b1cc-9991a6903c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tovuti_nav_user_groups&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>dd103138-04e0-4312-81b5-d620c09371cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tovuti_nav_user_groups']/a</value>
      <webElementGuid>dced16e5-bd00-49a4-a1e6-0f7526fe37fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'User Groups')]</value>
      <webElementGuid>37650a25-7514-494c-8b49-0d5d3f6bd62d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Profile Fields'])[1]/following::a[1]</value>
      <webElementGuid>fe51f294-bf9f-4d82-8e60-f06ca6b4d020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Manager'])[1]/following::a[2]</value>
      <webElementGuid>259eaabe-db3f-4c08-a9e3-f8e19957aa03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Teams'])[1]/preceding::a[1]</value>
      <webElementGuid>02c0b91d-1078-443d-8ea8-6366b9d62ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Importer'])[1]/preceding::a[2]</value>
      <webElementGuid>570e7c76-ce31-4c9e-8389-e7b939caf86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Groups']/parent::*</value>
      <webElementGuid>87f7d5ce-bc1c-4d55-ba35-e6217ebb3cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'index.php?option=com_users&amp;view=groups')])[2]</value>
      <webElementGuid>6d6318d3-9221-45cd-b5df-f0778fffe575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/ul/li[3]/a</value>
      <webElementGuid>90ab7181-f093-4f77-980b-8849b4188580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_users&amp;view=groups' and (text() = '
                                        User Groups                                                                                                                    ' or . = '
                                        User Groups                                                                                                                    ')]</value>
      <webElementGuid>4350d54b-6629-4826-8ce1-fb3868d213e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
