<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Instructions_fas fa-analytics</name>
   <tag></tag>
   <elementGuidId>bf1cb0e1-fb7c-4448-907a-430142f2e54b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-analytics</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menuItem-tovuti_nav_analytics']/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8802d659-9ee6-4bbd-986e-c01b89757bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-analytics</value>
      <webElementGuid>4bb7dd13-ba9a-48b2-9ccc-6d1fd091a0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuItem-tovuti_nav_analytics&quot;)/a[@class=&quot;nav-link active&quot;]/i[@class=&quot;fas fa-analytics&quot;]</value>
      <webElementGuid>5dada73a-90ff-4351-9504-51d38c6b2f30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menuItem-tovuti_nav_analytics']/a/i</value>
      <webElementGuid>2cca240e-1b1b-4de0-8914-61d42513a066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/i</value>
      <webElementGuid>96f8eec8-c9bb-4a07-a373-3c6aada78af1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
