<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_filtersearch</name>
   <tag></tag>
   <elementGuidId>00ff8c10-d29b-4f57-a60c-ca44137a843c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='filter_search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filter_search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1e55eb2-2baf-4c99-9061-083c1fde8680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b35e28c-dbda-4ec0-a468-47b2334579d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter[search]</value>
      <webElementGuid>52554301-4358-42ff-90b0-9c3588aff538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filter_search</value>
      <webElementGuid>07c0c33a-38f7-42c4-a16b-aee5c7a07304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-stools-search-string</value>
      <webElementGuid>1c9c30b2-1e51-40d9-9574-63fc32b94150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>d7bec001-a52d-4599-ada0-8b17595b11ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip848146</value>
      <webElementGuid>95e56fe3-8fdf-46a7-959f-a2cd550cf924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter_search&quot;)</value>
      <webElementGuid>ec5b4ffc-108d-4841-bb2a-bcdf29b5adff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='filter_search']</value>
      <webElementGuid>4a32de02-29f4-49ba-ab49-63bccf2e1d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='adminForm']/div/div/div/div/div/input</value>
      <webElementGuid>8ee2b30e-c4d3-44c2-bbbd-e7faa1852d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>d95224b4-8174-4991-b100-d9a1d21efc0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'filter[search]' and @id = 'filter_search' and @placeholder = 'Search']</value>
      <webElementGuid>710974eb-39ed-4b50-89ef-4ce25d63ec1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
