<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Action_1-source-forDisplay</name>
   <tag></tag>
   <elementGuidId>01bf556d-cc6b-4c0a-a000-975e793a31d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='1-jform_params_source-6452845a0187a-forDisplay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1-jform_params_source-6452845a0187a-forDisplay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d90228e-5c59-4328-a18e-ae373628548c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4fd57ba8-ac88-4b3a-b466-be2bfbdefbb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1-source-forDisplay</value>
      <webElementGuid>290b41f8-cf81-4eca-885d-0dd7db0cc374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1-jform_params_source-6452845a0187a-forDisplay</value>
      <webElementGuid>1e67739f-98af-44e3-b0db-818972919e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>77d65151-3d85-4b6c-8c81-8abe38e325e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-basepath</name>
      <type>Main</type>
      <value>https://clouddevelopmentresources.tovuti.io/</value>
      <webElementGuid>18d0f2cc-9544-4ce8-b20b-93dc1f5fcc59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-imagespath</name>
      <type>Main</type>
      <value>images/j70Eoet2sL68ByGSKDuCGHMTYwNjE0NjM2Mzc0NQ/</value>
      <webElementGuid>8599646b-3277-4410-b6fa-c638b91e71ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@change</name>
      <type>Main</type>
      <value>updateSelectedRowMedia('jform_params_source-6452845a0187a-forDisplay')</value>
      <webElementGuid>b433396d-0f69-435f-8238-d2d32d9481e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-large wf-media-input</value>
      <webElementGuid>51901f43-9ba7-4b99-a862-64523935d1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1-jform_params_source-6452845a0187a-forDisplay&quot;)</value>
      <webElementGuid>6fd81a8b-dc97-4e1a-b7b4-8a76ab386955</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1-jform_params_source-6452845a0187a-forDisplay']</value>
      <webElementGuid>a932774f-b6b5-4058-a235-a896c4590dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='files_table']/tbody/tr/td[3]/div/input</value>
      <webElementGuid>f28814cd-af1b-470a-8c65-dce679b4c02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/input</value>
      <webElementGuid>3c6c6d6b-91be-4706-9f85-f73af7f9acb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = '1-source-forDisplay' and @id = '1-jform_params_source-6452845a0187a-forDisplay']</value>
      <webElementGuid>1c3452c6-1f6b-4477-a344-37ba5e7f5dca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
