<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Points Categories</name>
   <tag></tag>
   <elementGuidId>5cfd6821-99fb-4471-9c05-6f5e2ef2f3b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tovuti_nav_learning_points_categories']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bb83cca0-b6f2-424b-8aa0-9be7237e4a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_axs&amp;view=points_categories</value>
      <webElementGuid>d0a1a50e-3cab-4d57-aa99-46d0e84f834a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>69b8267d-16c8-460e-8864-de7b8e0f4458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>86187097-5e56-4a51-a860-391e134a4063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Points Categories                                                                                                                    </value>
      <webElementGuid>fa0596b2-e0c6-4b22-aa15-d25f6762d0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tovuti_nav_learning_points_categories&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>f1eec9a9-28eb-46fe-a91b-fd2a168c7d29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tovuti_nav_learning_points_categories']/a</value>
      <webElementGuid>49659fff-a59d-44e0-9f0e-fa241aac2817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Points Categories')]</value>
      <webElementGuid>cf593d2f-6889-4470-8a7e-e90b08c309d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Certificate Designer'])[1]/following::a[1]</value>
      <webElementGuid>cee4ef5a-cd06-4446-ba19-5360f27a4600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Awards'])[1]/following::a[2]</value>
      <webElementGuid>f80dca63-c900-4b38-84b3-e3d63a88f909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/preceding::a[1]</value>
      <webElementGuid>9ca8ee2c-0c36-471a-b93e-9b17d52f8df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Points Categories']/parent::*</value>
      <webElementGuid>4ce767f9-173f-4efd-a575-05d857381778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?option=com_axs&amp;view=points_categories')]</value>
      <webElementGuid>a6fc6804-6b79-4a09-9a86-be0b173e8c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a</value>
      <webElementGuid>f7d66581-4437-4fff-94c2-bc4de88fc753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_axs&amp;view=points_categories' and (text() = '
                                        Points Categories                                                                                                                    ' or . = '
                                        Points Categories                                                                                                                    ')]</value>
      <webElementGuid>62674acf-35fa-4e80-bf3d-665143cdac58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
