<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Top Sales Person</name>
   <tag></tag>
   <elementGuidId>8131fe60-c0cf-4416-bbee-9645e79461be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='itemsList']/tbody/tr/td[3]/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.title > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db6dde94-4ddc-41fa-8919-eb9de18335b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_splms&amp;view=certificate&amp;id=2</value>
      <webElementGuid>8979b38a-0ec2-4ed8-ad1e-62c1da1939c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Top Sales Person</value>
      <webElementGuid>956ddfcf-1db4-4444-bd09-dcbc011f357b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemsList&quot;)/tbody[1]/tr[@class=&quot;row0&quot;]/td[3]/span[@class=&quot;title&quot;]/a[1]</value>
      <webElementGuid>e286bfa6-e19f-4a21-854a-8d5f709f8c8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='itemsList']/tbody/tr/td[3]/span/a</value>
      <webElementGuid>6ed68025-8484-4440-baab-8f13c43ff5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Top Sales Person')]</value>
      <webElementGuid>01e5ef0b-d6bc-4493-afe5-4923e8db265b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort Table By:'])[1]/following::a[5]</value>
      <webElementGuid>d401fdf6-6f51-48d0-b169-3db1a4293c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the ordering.'])[1]/following::a[5]</value>
      <webElementGuid>3d5f997a-7e26-4cb3-9693-98f920f3b24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Top Sales Person']/parent::*</value>
      <webElementGuid>725e2fed-0b12-44bd-a073-84372872af91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?option=com_splms&amp;view=certificate&amp;id=2')]</value>
      <webElementGuid>b3568681-5140-412a-9072-d419a409f8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>87e4653b-946d-42bd-a63d-54aa80a33b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_splms&amp;view=certificate&amp;id=2' and (text() = 'Top Sales Person' or . = 'Top Sales Person')]</value>
      <webElementGuid>d6d3e084-c673-4b40-bef2-84632d0fbfb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
