<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Test Automation Trainings</name>
   <tag></tag>
   <elementGuidId>941db2ed-195f-402b-8193-b998d2b4598a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.title > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='itemsList']/tbody/tr/td[3]/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>09426c25-d65b-4547-be1c-397c3b532409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_axs&amp;view=checklist&amp;id=5</value>
      <webElementGuid>c81b584f-ff9e-4774-bce2-2abb7d97946d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Automation Trainings</value>
      <webElementGuid>16a1af23-f554-4cc1-ab72-9b6ab807be3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemsList&quot;)/tbody[1]/tr[@class=&quot;row0&quot;]/td[3]/span[@class=&quot;title&quot;]/a[1]</value>
      <webElementGuid>d9342ebc-2ca4-46eb-bf23-7f33c6503825</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='itemsList']/tbody/tr/td[3]/span/a</value>
      <webElementGuid>5b1660d8-03a0-47cc-b485-fb8334080063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Test Automation Trainings')]</value>
      <webElementGuid>31850195-3942-4bff-b72d-7d02b5447b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort Table By:'])[1]/following::a[6]</value>
      <webElementGuid>c6c096c5-457d-4a04-8336-83a4daf3b7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the ordering.'])[1]/following::a[6]</value>
      <webElementGuid>e972578a-72f3-472e-884e-db27504ce119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test Automation Trainings']/parent::*</value>
      <webElementGuid>fb9ec55c-cbf2-44b7-b099-dd44b410c59c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?option=com_axs&amp;view=checklist&amp;id=5')]</value>
      <webElementGuid>95cb74ec-2955-4700-9ef2-067eac2099de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>0ab9c3cb-71ea-41ea-be52-0e633a207124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_axs&amp;view=checklist&amp;id=5' and (text() = 'Test Automation Trainings' or . = 'Test Automation Trainings')]</value>
      <webElementGuid>bdd7e166-9d35-4ca8-b092-82373d6e6e4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
