<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Your Points 26700_bw</name>
   <tag></tag>
   <elementGuidId>af0c4991-516b-4543-b7b3-13ea7f1b94ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='my-account']/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.bw</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7888c2f2-b1f3-424b-9ee6-08ccaad0c01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/j70Eoet2sL68ByGSKDuCGHMTYwNjE0NjM2Mzc0NQ/community/avatar/90e126055012e3e42f4357d7.jpg</value>
      <webElementGuid>973fedb9-fec0-4907-a96d-5275201e91e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bw</value>
      <webElementGuid>a20f55d8-2126-41df-bcc6-94af25c75bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>profile picture</value>
      <webElementGuid>6e249d25-9ac1-47e1-98f2-7315f057b33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-account&quot;)/a[@class=&quot;dropdown-toggles&quot;]/div[@class=&quot;comment-img&quot;]/img[@class=&quot;bw&quot;]</value>
      <webElementGuid>9a5bd101-f823-4a25-a481-bf570eda9ec6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='my-account']/a/div/img</value>
      <webElementGuid>bd0e158c-69a0-4290-8a73-cdde892fb6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='profile picture']</value>
      <webElementGuid>f265c024-be0f-42b1-8f23-79ad82460955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>4fda5f45-3728-4304-bc1a-cfc713ce2680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/j70Eoet2sL68ByGSKDuCGHMTYwNjE0NjM2Mzc0NQ/community/avatar/90e126055012e3e42f4357d7.jpg' and @alt = 'profile picture']</value>
      <webElementGuid>78c23ca7-3bae-4f55-b0c1-7f67cf585d92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
