<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Administrator Options</name>
   <tag></tag>
   <elementGuidId>d78ea24f-42a3-46c1-94f7-db978456ac98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='my-account-menu']/li/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.my-account-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4e7b3783-aeac-444f-9752-182c3fba1209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my-account-label</value>
      <webElementGuid>5482a4f7-085c-4c86-b9db-a2847b350611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administrator Options</value>
      <webElementGuid>a6c5f92f-93e3-482c-8aa0-0d9ae5fa06a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-account-menu&quot;)/li[1]/a[1]/span[@class=&quot;my-account-label&quot;]</value>
      <webElementGuid>22379dfb-c7c3-490b-998b-41372a803707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='my-account-menu']/li/a/span[2]</value>
      <webElementGuid>67ea98b0-7de0-4fa7-9feb-24896cf37e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Points: 26700'])[1]/following::span[3]</value>
      <webElementGuid>08dc19e4-b41c-4f54-aa56-05403ce42a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rodel Agpaoa'])[1]/following::span[4]</value>
      <webElementGuid>1d27a7db-d75f-4e59-b365-6b70fffe169d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Profile'])[1]/preceding::span[2]</value>
      <webElementGuid>7bcd3b3d-f1fb-4710-9771-7c4955f8ba30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing Manager'])[1]/preceding::span[4]</value>
      <webElementGuid>4de7b6a0-a4df-4073-ab44-5044aac31d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administrator Options']/parent::*</value>
      <webElementGuid>ffa8975b-a990-4a0e-aebc-3bb49d1d6ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>c2588c01-c588-49cf-8bd1-8085ffdba4e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Administrator Options' or . = 'Administrator Options')]</value>
      <webElementGuid>e639a7e3-da0f-4c37-a9ae-e4611e54bfc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
