<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login_tov_login-left_content</name>
   <tag></tag>
   <elementGuidId>a6db6eda-5bf1-4eb6-9c4d-977a135884fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tov_login-left_content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a3b08671-ddfc-4c11-aff1-053fdfadca64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tov_login-left_content</value>
      <webElementGuid>3873c4e2-251f-44bd-a2c9-8e69a4d9fcf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;w-mod-js&quot;]/body[1]/div[@class=&quot;tov_login-container&quot;]/div[@class=&quot;tov_login-left&quot;]/div[@class=&quot;tov_login-left_content&quot;]</value>
      <webElementGuid>f172e808-95da-4e1c-a256-9ee842628a49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::div[2]</value>
      <webElementGuid>4a26c4f8-3cd7-47b4-aa04-48c25b10b733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset Password'])[1]/preceding::div[2]</value>
      <webElementGuid>8e862888-4b1a-49db-b8da-a704b3c0c93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>0dedd207-6478-45d0-8221-38073a20f1e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
