<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Register_login_button</name>
   <tag></tag>
   <elementGuidId>612860b5-725e-4a06-b183-311c45bc4f42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd01f6bf-8772-405e-b4ea-d85a3caeeb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c9d28467-6fe5-447f-9c2c-b364535d3980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>41c03b94-5d17-4330-99e2-4e3225b4f7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wait</name>
      <type>Main</type>
      <value>Please wait...</value>
      <webElementGuid>13ca2f17-026d-4c9b-a4fe-7c3e8f47aca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login_button</value>
      <webElementGuid>98648131-de1b-4cda-8551-1a9486f986d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tov_login-button w-button</value>
      <webElementGuid>3687c4c0-dc7a-44a1-a060-4ad06899172a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login_button&quot;)</value>
      <webElementGuid>c2934e4a-5e73-4fd3-939a-a6974575c133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login_button']</value>
      <webElementGuid>3193994b-a21c-4c24-865b-14005abc962a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tov_login-form']/div/div/input</value>
      <webElementGuid>1fdd0672-32c3-4e59-9fdd-f85b9fffade1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>7f48f8eb-2579-41c9-a50c-5a8135bb311c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'login_button']</value>
      <webElementGuid>4d03a9a8-4e2e-4b7d-87f3-dd439ac06e5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
