<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_User Profile Fields</name>
   <tag></tag>
   <elementGuidId>a55c51e7-f518-42ab-9e0a-2a476591a865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tovuti_nav_configuration_profile_fields']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f74a1a62-61c8-48eb-ad6e-a3bdebc1a74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_community&amp;view=profiles</value>
      <webElementGuid>445c74c5-d607-43e5-bf65-c8eecdc0d882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>dffcd5df-1d17-4e9a-a0e4-b9f1da8a09bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>63d8a3bb-1b43-483c-b36b-d5e7577615f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        User Profile Fields                                                                                                                    </value>
      <webElementGuid>6c73fd32-7230-4234-9269-73151ccb4731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tovuti_nav_configuration_profile_fields&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>a31bcc22-6216-4171-924f-1ddd2cec350c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tovuti_nav_configuration_profile_fields']/a</value>
      <webElementGuid>1f5d6c11-8278-4da6-aca7-5ce289e177f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'User Profile Fields')]</value>
      <webElementGuid>ab9396a3-c1a0-487f-a1ae-53a228436fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Manager'])[1]/following::a[1]</value>
      <webElementGuid>af86c4a4-b6cd-4a4b-9254-8b51f1a91831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Groups'])[1]/preceding::a[1]</value>
      <webElementGuid>7111753f-b439-42c9-abd8-aab3d88afa6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Teams'])[1]/preceding::a[2]</value>
      <webElementGuid>578aca89-0dce-410f-8b20-e44a8a098814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Profile Fields']/parent::*</value>
      <webElementGuid>841a5902-8975-4f9f-a422-4999538bace2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?option=com_community&amp;view=profiles')]</value>
      <webElementGuid>38aad0f7-8635-4bb7-872c-42a2162cb1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/ul/li[2]/a</value>
      <webElementGuid>5b832225-913a-4ebc-9343-c2d87e81ec5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_community&amp;view=profiles' and (text() = '
                                        User Profile Fields                                                                                                                    ' or . = '
                                        User Profile Fields                                                                                                                    ')]</value>
      <webElementGuid>1f573120-b4a0-4f13-89f8-639afa5b675b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
