<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search_icon-search</name>
   <tag></tag>
   <elementGuidId>00ccd874-3539-437b-901f-54d511d1e5ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.icon-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='adminForm']/div/div/div/div/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fd1c278e-ac46-4e0e-ade3-683bf6bc268c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-search</value>
      <webElementGuid>616e341d-ad3a-4b3d-8d2a-916d7de473cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adminForm&quot;)/div[@class=&quot;js-stools clearfix&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;js-stools-container-bar&quot;]/div[@class=&quot;float-start&quot;]/div[@class=&quot;input-group&quot;]/button[@class=&quot;btn border&quot;]/span[@class=&quot;icon-search&quot;]</value>
      <webElementGuid>0d7a4de2-4a08-4ec8-968c-133519e4eb06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='adminForm']/div/div/div/div/div/button/span</value>
      <webElementGuid>33929ae1-cc99-430a-80b9-146467d966ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/button/span</value>
      <webElementGuid>f7b3314b-e5bb-41d5-b492-bcfbc0f54027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
