<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Rootcause Analysis Tools and Methods</name>
   <tag></tag>
   <elementGuidId>3e23a0ed-cc84-4f5e-807f-2248dcda257a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.title > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='itemsList']/tbody/tr/td[4]/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d938110d-eb93-4f3e-a5d5-174d4fd19e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_splms&amp;view=course&amp;id=178</value>
      <webElementGuid>af6ae9dd-a5e5-45a2-8a62-f48b0158fb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rootcause Analysis Tools and Methods</value>
      <webElementGuid>d790030d-6d37-400f-94a8-6d2906091992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemsList&quot;)/tbody[1]/tr[@class=&quot;row0&quot;]/td[4]/span[@class=&quot;title&quot;]/a[1]</value>
      <webElementGuid>913c68de-23d6-4343-9c82-db86ba99c80a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='itemsList']/tbody/tr/td[4]/span/a</value>
      <webElementGuid>d22cdc71-b40e-4c68-8a68-9ea1dce3bdc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Rootcause Analysis Tools and Methods')]</value>
      <webElementGuid>4ce551c8-47c1-49fb-8d08-4ac9db5d88dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort Table By:'])[1]/following::a[9]</value>
      <webElementGuid>f6076b3e-a28b-4dd1-bbec-84a4b83ec59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the ordering.'])[1]/following::a[9]</value>
      <webElementGuid>8019dd77-0f55-4b58-bafd-6728a1253adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Courses'])[2]/preceding::a[1]</value>
      <webElementGuid>92a3f3f2-5136-4902-97cf-0704ab975478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rootcause Analysis Tools and Methods']/parent::*</value>
      <webElementGuid>8664b501-6dec-42e4-8608-4bf874a9ba9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?option=com_splms&amp;view=course&amp;id=178')]</value>
      <webElementGuid>1ab08c47-ca7b-41e9-bc57-9ca08f5ce491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>e0d0fd40-c2b6-450f-9835-6bb70366172b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_splms&amp;view=course&amp;id=178' and (text() = 'Rootcause Analysis Tools and Methods' or . = 'Rootcause Analysis Tools and Methods')]</value>
      <webElementGuid>efbb0569-2aae-487a-8814-fb0f6cf5d24d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
