<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Your Points 26700_bw</name>
   <tag></tag>
   <elementGuidId>71d32363-033d-4346-bd1b-f6728e483929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.bw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='my-account']/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3c847483-aa6f-4e88-a3be-acad895d83f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/j70Eoet2sL68ByGSKDuCGHMTYwNjE0NjM2Mzc0NQ/community/avatar/90e126055012e3e42f4357d7.jpg</value>
      <webElementGuid>349eea03-9418-4a43-8dff-dca273672e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bw</value>
      <webElementGuid>9c32c5fc-2e0b-4f3d-b4dd-6b684eec8793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>profile picture</value>
      <webElementGuid>8ee49536-06b2-49f2-9d8a-a6f18d5a5f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-account&quot;)/a[@class=&quot;dropdown-toggles&quot;]/div[@class=&quot;comment-img&quot;]/img[@class=&quot;bw&quot;]</value>
      <webElementGuid>755e2139-9219-437f-ba0e-7daec380f115</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='my-account']/a/div/img</value>
      <webElementGuid>c8ef8066-d0c4-4925-8531-2d88aeb51662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='profile picture']</value>
      <webElementGuid>9c384543-0ef2-40a3-842f-795db6266af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>abf33f76-c457-4fba-b737-920c3c3e83c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/j70Eoet2sL68ByGSKDuCGHMTYwNjE0NjM2Mzc0NQ/community/avatar/90e126055012e3e42f4357d7.jpg' and @alt = 'profile picture']</value>
      <webElementGuid>04c45caa-175c-40ed-8685-f3aadd3bbe5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
