<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Instructions_fas fa-users</name>
   <tag></tag>
   <elementGuidId>a5b131a4-92eb-4685-98f5-f4b6dc68f548</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menuItem-tovuti_nav_people']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-users</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>675495ec-9283-4cbb-a6c3-b7208237eb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-users</value>
      <webElementGuid>61bb6f1c-b30a-4148-aa02-0cf319ca6abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuItem-tovuti_nav_people&quot;)/a[@class=&quot;nav-link&quot;]/i[@class=&quot;fas fa-users&quot;]</value>
      <webElementGuid>d9169862-83e7-4ad0-80be-4edf0c7a4421</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menuItem-tovuti_nav_people']/a/i</value>
      <webElementGuid>303bb9e7-56d1-4d3e-9a94-65306c180305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a/i</value>
      <webElementGuid>64bb5531-e733-43f6-8295-feaca387778e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
