<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_LJMB Leadership Training Badge - Men</name>
   <tag></tag>
   <elementGuidId>9621ec99-0747-4871-b077-d736eed11b74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='itemsList']/tbody/tr[8]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>dc696ce6-3613-4cdc-b370-f31a34a21219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LJMB Leadership Training Badge - Men</value>
      <webElementGuid>6cf18e95-306b-4307-b1e2-ae56419cec21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemsList&quot;)/tbody[1]/tr[@class=&quot;row1&quot;]/td[3]</value>
      <webElementGuid>c763cf89-fc02-43ab-ade5-fa79820197e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='itemsList']/tbody/tr[8]/td[3]</value>
      <webElementGuid>4458e131-8fce-46de-b422-88d5f57b2cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='badge'])[4]/following::td[3]</value>
      <webElementGuid>0eaf1491-b95d-4ad3-8dca-0d727a841693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed LJMB Leadership Training'])[1]/following::td[4]</value>
      <webElementGuid>4f724124-94ce-4c8d-99fa-897942a20977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completed LJMB Leadership Training'])[2]/preceding::td[1]</value>
      <webElementGuid>8c264586-86ab-4b6a-83c4-62a8057c4005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[3]</value>
      <webElementGuid>39544cc5-4aaa-4b03-ab69-61d0eb7295a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'LJMB Leadership Training Badge - Men' or . = 'LJMB Leadership Training Badge - Men')]</value>
      <webElementGuid>e6e6412a-8bbd-4ac8-ad46-7da5151fce09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
