<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Quizzes</name>
   <tag></tag>
   <elementGuidId>5d2e8396-5064-4ed6-908b-bc09a2e1f23c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tovuti_nav_quizzes > a.nav-link.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tovuti_nav_quizzes']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa41c6ce-1e57-4291-9548-2889c79d6be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_splms&amp;view=quizquestions</value>
      <webElementGuid>eabc9fce-8692-4b03-bbf6-4c2045625e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link active</value>
      <webElementGuid>d6be8016-95c7-436b-ae17-ef75f7cb12c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>dffb3f44-0462-40cf-9852-ba1239cefd7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Quizzes                                                                                                                    </value>
      <webElementGuid>4c3ade65-9a14-4ae6-9863-2e0e00fdae81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tovuti_nav_quizzes&quot;)/a[@class=&quot;nav-link active&quot;]</value>
      <webElementGuid>d8f68d73-3636-436e-879a-ae521a382b17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tovuti_nav_quizzes']/a</value>
      <webElementGuid>c43649e4-d707-4f45-ad1f-7c6432f5795e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Quizzes')]</value>
      <webElementGuid>196bd5f4-7208-4b06-9bf1-88a50a0ba7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assessments'])[1]/following::a[1]</value>
      <webElementGuid>f2fea16b-894c-44c2-be92-7bb52467b34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eLearning Packages'])[1]/following::a[1]</value>
      <webElementGuid>f32432fa-4eb4-4bbe-adc3-23971345ca27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surveys'])[1]/preceding::a[1]</value>
      <webElementGuid>09dc049b-d17a-4bf7-8e03-774f5697aa57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media'])[1]/preceding::a[2]</value>
      <webElementGuid>aa0e860d-6f6d-4373-8ce0-be92fa0a9fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quizzes']/parent::*</value>
      <webElementGuid>c31a4246-3158-4675-b504-37c788e989a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?option=com_splms&amp;view=quizquestions')]</value>
      <webElementGuid>b17c1d6e-e5f8-448a-8851-cbc2c2356500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div[2]/ul/li[3]/a</value>
      <webElementGuid>75173dbf-a085-400b-8810-8a41212476fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_splms&amp;view=quizquestions' and (text() = '
                                        Quizzes                                                                                                                    ' or . = '
                                        Quizzes                                                                                                                    ')]</value>
      <webElementGuid>6ac23f00-10b3-4e73-83cc-42d06491efac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
