<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Surveys</name>
   <tag></tag>
   <elementGuidId>f80f4862-5737-41ec-8fb4-74a86a477a53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tovuti_nav_surveys']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>69b8cff2-cfd3-4414-89fa-56da88a70c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_axs&amp;view=surveys</value>
      <webElementGuid>233a6de1-030d-4d6d-953c-8f186327f013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>89f3f4af-8fc4-4fc9-8cb2-202875c97c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>0052610b-93cf-4125-90c7-9363dc758a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Surveys                                                                                                                    </value>
      <webElementGuid>87ce86d9-1296-4fb8-af04-22678944acfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tovuti_nav_surveys&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>0435bf64-f32d-4357-a3f3-fdf1145e35c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tovuti_nav_surveys']/a</value>
      <webElementGuid>6ba4733c-7417-4232-b1d4-1cd78945dbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Surveys')]</value>
      <webElementGuid>e87afbee-771b-4204-87e0-be5db07b5634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quizzes'])[1]/following::a[1]</value>
      <webElementGuid>24a0ac2f-f911-4013-ad55-c7acef170b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assessments'])[1]/following::a[2]</value>
      <webElementGuid>ca533f8c-8231-4c64-928f-b1f4d3bf98fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media'])[1]/preceding::a[1]</value>
      <webElementGuid>c0716b3e-2d86-4545-98c9-6bcc07d48ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Media Items'])[1]/preceding::a[1]</value>
      <webElementGuid>603e3a15-a95d-4472-9710-9490c02b2afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Surveys']/parent::*</value>
      <webElementGuid>79010034-2bbb-4447-be31-c5494b30393b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?option=com_axs&amp;view=surveys')]</value>
      <webElementGuid>27b8244e-fb63-4c0b-8baa-abf9930c4059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div[2]/ul/li[4]/a</value>
      <webElementGuid>ede44f8c-1af0-4716-b88f-0fbbcb03674b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_axs&amp;view=surveys' and (text() = '
                                        Surveys                                                                                                                    ' or . = '
                                        Surveys                                                                                                                    ')]</value>
      <webElementGuid>f2645f45-5e92-4b73-abfa-234d3003557a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
