<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Duplicate Lesson(s)_icon-search text-muted</name>
   <tag></tag>
   <elementGuidId>6364f48a-5398-4575-b710-0521c0b9fefa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon-search.text-muted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='filter-bar']/div/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d3654ad4-8d97-4fd6-aac8-cfadb3c7e46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-search text-muted</value>
      <webElementGuid>41dccd91-eb39-418b-b7b2-1b59a9676468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter-bar&quot;)/div[@class=&quot;float-start me-2&quot;]/div[@class=&quot;input-group&quot;]/button[@class=&quot;btn border&quot;]/i[@class=&quot;icon-search text-muted&quot;]</value>
      <webElementGuid>dac521c0-e32a-49a5-a040-ae13df938f9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filter-bar']/div/div/button/i</value>
      <webElementGuid>798543f6-1e93-430c-bada-d364a93b7144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button/i</value>
      <webElementGuid>68610107-1bb4-4f41-8350-220732488f46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
