<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Activity Reports</name>
   <tag></tag>
   <elementGuidId>563663b5-db63-444a-9f91-9a1bb88d874e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tovuti_nav_analytics_activity_reports']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7661b7ae-3834-4f1b-a17d-bda8bff822aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_reports&amp;view=activity_reports</value>
      <webElementGuid>2351d46c-4bf9-4205-888b-3bf6bd0cc312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>9c93b03f-c704-4bc7-afcc-3a2d29bc0cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>9715bbba-024f-4518-bc34-208f736506af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Activity Reports                                                                                                                    </value>
      <webElementGuid>2d1b830a-9f04-4429-8367-9002ec343e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tovuti_nav_analytics_activity_reports&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>ce8fa2a6-c1ab-4ec7-a881-9d16e851ef69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tovuti_nav_analytics_activity_reports']/a</value>
      <webElementGuid>6f46041c-8a5b-4073-bf06-326b0f785e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Activity Reports')]</value>
      <webElementGuid>803358a3-5f99-4f88-933b-4817a38410a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report Builder'])[1]/following::a[1]</value>
      <webElementGuid>656d1b08-0033-4a0d-a936-da08aca324de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Reports'])[1]/preceding::a[1]</value>
      <webElementGuid>325e13ac-427d-44c1-a08a-184a91450f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity Dashboards'])[1]/preceding::a[2]</value>
      <webElementGuid>6fd7f36c-efc1-4295-bca9-34010892cb40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Activity Reports']/parent::*</value>
      <webElementGuid>dc89f1ba-c4f0-48de-8a2c-856786653adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?option=com_reports&amp;view=activity_reports')]</value>
      <webElementGuid>b48bf119-ee73-4d50-a9ba-bb0beafd263f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/ul/li[2]/a</value>
      <webElementGuid>f26f71ce-85bb-4ffa-bb0c-b22e59a9230a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_reports&amp;view=activity_reports' and (text() = '
                                        Activity Reports                                                                                                                    ' or . = '
                                        Activity Reports                                                                                                                    ')]</value>
      <webElementGuid>932ae355-0159-4404-a835-cfff9b5068c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
