<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Test Assignment</name>
   <tag></tag>
   <elementGuidId>05a6dda6-76f9-4a4e-9585-4dbf03ecf056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.title > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='itemsList']/tbody/tr/td[2]/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c367fd52-0979-4f17-9976-4eb0c49d4317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_splms&amp;view=courseassignment&amp;id=2</value>
      <webElementGuid>d769e12e-c58b-4e1c-83dd-60970698f2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Assignment</value>
      <webElementGuid>662417db-0859-4b97-86e6-0eb1b571b08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemsList&quot;)/tbody[1]/tr[@class=&quot;row0&quot;]/td[2]/span[@class=&quot;title&quot;]/a[1]</value>
      <webElementGuid>4ad47c17-f0f7-4fbd-a3b9-48f20f31665a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='itemsList']/tbody/tr/td[2]/span/a</value>
      <webElementGuid>1e4c2e73-6e42-4f1b-8d5d-511199d5d13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Test Assignment')]</value>
      <webElementGuid>788cadfd-611e-46a5-99a6-977f11c639b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort Table By:'])[1]/following::a[6]</value>
      <webElementGuid>477212ae-7561-460a-94e6-22c792f919fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the ordering.'])[1]/following::a[6]</value>
      <webElementGuid>8818b45a-1371-470c-a4e7-1b3cb6f0ed84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test Assignment']/parent::*</value>
      <webElementGuid>b357d6cc-6260-4e65-b383-194e770e28de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?option=com_splms&amp;view=courseassignment&amp;id=2')]</value>
      <webElementGuid>25fc87d5-648c-4b57-a0a5-42b815dca296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>95ebe267-e751-4609-a393-c04890c0af45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_splms&amp;view=courseassignment&amp;id=2' and (text() = 'Test Assignment' or . = 'Test Assignment')]</value>
      <webElementGuid>f24324a6-b213-4f1c-bb57-9b219a9e44a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
