<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_User Profile Fields</name>
   <tag></tag>
   <elementGuidId>e815a03a-8565-410e-8931-e653c7ecdde3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tovuti_nav_configuration_profile_fields']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c08b8cf1-c239-4487-919a-30852d8dd57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_community&amp;view=profiles</value>
      <webElementGuid>d88bc720-e547-4f78-82b4-a7f2067ca299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>de48a155-b3d0-4feb-b74f-0646598b7a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>b2fde3da-a9a7-4efe-99dd-888c238ff475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        User Profile Fields                                                                                                                    </value>
      <webElementGuid>af074dc9-b677-49ab-8a0c-c1910fb7f524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tovuti_nav_configuration_profile_fields&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>04ce426d-7c46-49a0-9d69-f98be2a90607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tovuti_nav_configuration_profile_fields']/a</value>
      <webElementGuid>e97cc95d-436f-4557-abd0-9fd4fb9d3df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'User Profile Fields')]</value>
      <webElementGuid>35b1a6a9-19c7-40fc-b78a-ce3442a1a6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Manager'])[1]/following::a[1]</value>
      <webElementGuid>6a364f4a-fc05-4e03-9620-55af1fc59ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Groups'])[1]/preceding::a[1]</value>
      <webElementGuid>a2ac6950-1e9d-49ff-8ad9-12909e158245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Teams'])[1]/preceding::a[2]</value>
      <webElementGuid>67d191a0-e4b1-4570-ba91-9e19b12cfc33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Profile Fields']/parent::*</value>
      <webElementGuid>de5c1464-8580-43f5-9a84-f184e4f087ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?option=com_community&amp;view=profiles')]</value>
      <webElementGuid>1284abad-7611-485d-9bec-37e01d8ada95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/ul/li[2]/a</value>
      <webElementGuid>4d7d2112-04cd-4542-9abc-fc3b1e90d29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_community&amp;view=profiles' and (text() = '
                                        User Profile Fields                                                                                                                    ' or . = '
                                        User Profile Fields                                                                                                                    ')]</value>
      <webElementGuid>5a67a4d5-57d6-460d-9338-a1c3aff8957c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
