<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Rodel Agpaoa</name>
   <tag></tag>
   <elementGuidId>e5ff750e-e8d8-4f4a-a484-c7484a3c99a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='details']/div/div/div/div/div/div/div[2]/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.user-account-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>1012e502-36f0-4543-9167-1b9e8b5b0e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user-account-name</value>
      <webElementGuid>b561907a-f17f-4cde-94f7-35fd565f42a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rodel Agpaoa</value>
      <webElementGuid>67300777-e00a-4a6c-9d7a-417101a1189b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details&quot;)/div[@class=&quot;container-fluid user-details&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9&quot;]/div[@class=&quot;row&quot;]/h4[@class=&quot;user-account-name&quot;]</value>
      <webElementGuid>bb49c12e-ed1e-4e3b-beeb-349c561a4a72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='details']/div/div/div/div/div/div/div[2]/div/h4</value>
      <webElementGuid>588aeb98-0c19-4a39-8292-5d55fb861d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API Tokens'])[1]/following::h4[1]</value>
      <webElementGuid>4a40b169-75ce-4ab8-8bc8-cae10d1fae17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comments'])[1]/following::h4[1]</value>
      <webElementGuid>92e15a3f-7196-46c7-a7a7-3000db8592b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This Week'])[1]/preceding::h4[1]</value>
      <webElementGuid>137a6aed-db02-4c06-8a55-8fffaf94b44b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Profile'])[1]/preceding::h4[1]</value>
      <webElementGuid>263c9250-4e62-467a-af1d-22341c67b80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/h4</value>
      <webElementGuid>8a305510-44d8-4578-b4fd-3fa32d244eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Rodel Agpaoa' or . = 'Rodel Agpaoa')]</value>
      <webElementGuid>1dda0677-85fe-4c09-bcff-e566d952e878</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
