<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admin Roles  Permissions</name>
   <tag></tag>
   <elementGuidId>ca6165dd-b24d-4834-89ed-ea3bd0f19ebf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tovuti_nav_user_admin_permissioning']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8be4c33a-daa9-4b41-bfd7-a9b698c54ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_permissioning&amp;view=groups</value>
      <webElementGuid>b6da29e6-f5fb-4b57-954d-b5a1177fa703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>8fef5e23-1960-4795-8c36-00d2fcc214fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>8cfcbbe3-e58c-4b88-a258-64d3d7ea1768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Admin Roles &amp; Permissions                                                                                                                    </value>
      <webElementGuid>5d25a9b3-5278-4b30-956c-a496a3275011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tovuti_nav_user_admin_permissioning&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>0d980787-2b0a-4c92-ba6d-7cc6a3f04227</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tovuti_nav_user_admin_permissioning']/a</value>
      <webElementGuid>32a93bd9-bbac-4140-9b6c-c86fe0df75bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Admin Roles &amp; Permissions')]</value>
      <webElementGuid>905b88c9-e301-45db-a8c8-241382498cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access Levels'])[1]/following::a[1]</value>
      <webElementGuid>884721f7-607b-4d6f-9861-f04ce8661049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Note Categories'])[1]/following::a[2]</value>
      <webElementGuid>2c1cea48-06fb-431e-b632-d3705da6e20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instructors'])[1]/preceding::a[1]</value>
      <webElementGuid>fe18f14f-4ad2-45a2-af56-6229f78bd984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admin Roles &amp; Permissions']/parent::*</value>
      <webElementGuid>1bf02518-0d80-4cfe-94ef-5407583136dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?option=com_permissioning&amp;view=groups')]</value>
      <webElementGuid>f95bb881-c4ec-4b8c-a1c2-1937b636d9c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/ul/li[9]/a</value>
      <webElementGuid>da27aaa7-47fb-451c-8c3d-72c010d5e898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_permissioning&amp;view=groups' and (text() = '
                                        Admin Roles &amp; Permissions                                                                                                                    ' or . = '
                                        Admin Roles &amp; Permissions                                                                                                                    ')]</value>
      <webElementGuid>a7a53f41-578a-43bb-849c-f3d60d74f5c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
