<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Public</name>
   <tag></tag>
   <elementGuidId>ae0d0e6a-7601-4d05-90bf-d56ce5b89113</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='levelList']/tbody/tr/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1fddf016-c175-4d51-bbe4-9a8c27bcb85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/administrator/index.php?option=com_users&amp;task=level.edit&amp;id=1</value>
      <webElementGuid>bf2bd033-915e-4418-a4fd-29e3192da868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								Public</value>
      <webElementGuid>170148b9-7b5a-47e1-80ae-65be568e723f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;levelList&quot;)/tbody[@class=&quot;ui-sortable&quot;]/tr[@class=&quot;row0 dndlist-sortable&quot;]/td[3]/a[1]</value>
      <webElementGuid>8926a6f5-43ee-40fd-87e9-9cf417b7b88e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='levelList']/tbody/tr/td[3]/a</value>
      <webElementGuid>6ac9be4d-59ec-435a-a713-2d3d13a0c584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Public')]</value>
      <webElementGuid>7ac9463e-bedb-449a-ab35-1fbf93a9e69c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Groups Having Viewing Access'])[1]/following::a[2]</value>
      <webElementGuid>d0ba628e-d7f7-4cdf-ba9d-77a7712e79b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::a[4]</value>
      <webElementGuid>5a1b134f-be58-4ee6-94c2-01002d63d8e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public'])[2]/preceding::a[1]</value>
      <webElementGuid>54809674-4bed-44fd-9e4c-c00f8a88c9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Super Admin'])[1]/preceding::a[1]</value>
      <webElementGuid>1b097280-e8b3-45a7-a895-c9d8fa026876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Public']/parent::*</value>
      <webElementGuid>1bf00124-0854-42b6-8c56-ee7b712e1415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/administrator/index.php?option=com_users&amp;task=level.edit&amp;id=1')]</value>
      <webElementGuid>360e4200-2955-43dc-99d2-02f64ee4962d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>b33e84d4-49cf-4ff7-a2c9-4ca55bcec2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/administrator/index.php?option=com_users&amp;task=level.edit&amp;id=1' and (text() = '
								Public' or . = '
								Public')]</value>
      <webElementGuid>261674b0-6fbc-457a-9c2a-0e918e900f14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
