<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search_icon-search</name>
   <tag></tag>
   <elementGuidId>192394c1-9ad7-4727-a579-2c8c5a4afb53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='j-main-container']/div/div/div/div/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.icon-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f3131b6e-6083-4b5b-8fe3-14e68881d9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-search</value>
      <webElementGuid>93741462-e1d5-477a-af9b-0950999dbbae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j-main-container&quot;)/div[@class=&quot;js-stools clearfix&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;js-stools-container-bar&quot;]/div[@class=&quot;float-start&quot;]/div[@class=&quot;input-group&quot;]/button[@class=&quot;btn border&quot;]/span[@class=&quot;icon-search&quot;]</value>
      <webElementGuid>9e378162-c373-4e72-af8f-689819d6698c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='j-main-container']/div/div/div/div/div/button/span</value>
      <webElementGuid>a5ca4bac-81c5-4f92-8ad9-e777218da52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/button/span</value>
      <webElementGuid>295464a9-8327-42b4-bde5-e7d1529fb6c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
