<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Billing</name>
   <tag></tag>
   <elementGuidId>54828ffe-88b6-49ec-badd-958e6aa98cc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='categoryList']/tbody/tr/td[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(4) > a.hasTooltip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9551ad6-7638-4374-b36d-e48309fa6916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hasTooltip</value>
      <webElementGuid>8846252a-b718-4465-a074-0d41a6eb2969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=8&amp;extension=com_users</value>
      <webElementGuid>e0c0a76f-5714-4e24-b2ad-d7ff5cf59e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>90d0c892-9539-41e2-abe9-7723ac7f5663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip515732</value>
      <webElementGuid>80b90aa2-4973-47c5-86cf-b2701c10c92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Billing</value>
      <webElementGuid>4019abb3-d751-4683-b1c7-0e890112c7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categoryList&quot;)/tbody[@class=&quot;ui-sortable&quot;]/tr[@class=&quot;row0 dndlist-sortable&quot;]/td[4]/a[@class=&quot;hasTooltip&quot;]</value>
      <webElementGuid>ea169168-6439-4ca7-b33a-18961ab12c2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='categoryList']/tbody/tr/td[4]/a</value>
      <webElementGuid>7ff2d6b1-9518-4962-a09f-9a3fc6773bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Billing')]</value>
      <webElementGuid>d3952d9d-8abc-4043-8525-5fddd23b5f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trash'])[1]/following::a[1]</value>
      <webElementGuid>e1d9ca48-07f2-4c17-aadf-8405c5fec904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archive'])[1]/following::a[2]</value>
      <webElementGuid>d594a9a5-b505-4643-95cf-ba2732eaaa96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alias'])[1]/preceding::a[1]</value>
      <webElementGuid>10484cf7-aacb-4bd1-9415-de722bae964a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Billing']/parent::*</value>
      <webElementGuid>20a9f295-6f18-4aa7-8607-d119a4b18992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=8&amp;extension=com_users')]</value>
      <webElementGuid>387ec66c-fa70-47b4-8d46-b9cbc6d48238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a</value>
      <webElementGuid>1ab8d9cd-e70f-48bf-833a-95916644df38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/administrator/index.php?option=com_categories&amp;task=category.edit&amp;id=8&amp;extension=com_users' and (text() = '
										Billing' or . = '
										Billing')]</value>
      <webElementGuid>5fb736a3-6f0d-4d6d-a31e-b4738f9d05b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
