<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search_icon-search</name>
   <tag></tag>
   <elementGuidId>a8cdf93d-ccbc-4e97-ae93-92ec607ac96a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='j-main-container']/div/div/div/div/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.icon-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6faf1553-eca2-4c8f-9556-50a26a178761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-search</value>
      <webElementGuid>4f5e7a0a-9cbf-414b-9c92-30636e520e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j-main-container&quot;)/div[@class=&quot;js-stools clearfix&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;js-stools-container-bar&quot;]/div[@class=&quot;float-start&quot;]/div[@class=&quot;input-group&quot;]/button[@class=&quot;btn border&quot;]/span[@class=&quot;icon-search&quot;]</value>
      <webElementGuid>16207142-aefd-4833-aaa2-23de4b145308</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='j-main-container']/div/div/div/div/div/button/span</value>
      <webElementGuid>86f9c820-3626-4a1b-a04c-4a593a2b4f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/button/span</value>
      <webElementGuid>43f71a69-03aa-4b01-a3c0-8cb2430330f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
