<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Activity Dashboards</name>
   <tag></tag>
   <elementGuidId>f0af5add-427a-4246-9df5-d3bca1c910b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tovuti_nav_analytics_activity_dashboards']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a6dbcfde-b429-4962-a84f-c68c72130665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.php?option=com_reports&amp;view=activity_dashboards</value>
      <webElementGuid>07333ccb-6676-4f98-8cb5-94e8635b7161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>b16b0fbe-c618-4d54-866e-877b549f57bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>08f19ae7-cd99-4305-8f70-030b67f10fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Activity Dashboards                                                                                                                    </value>
      <webElementGuid>f1695e15-caf0-476b-941a-d39834a484cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tovuti_nav_analytics_activity_dashboards&quot;)/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>480605e8-d81e-4e4c-9636-1cb904147c4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tovuti_nav_analytics_activity_dashboards']/a</value>
      <webElementGuid>91c6aadd-9bd0-498e-aa7c-5795bae4f326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Activity Dashboards')]</value>
      <webElementGuid>8fca1079-2ed5-4e6b-9cca-71201e8ae5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Reports'])[1]/following::a[1]</value>
      <webElementGuid>9ac31c3b-d194-4b0d-bb58-7f6f6b92d20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity Reports'])[1]/following::a[2]</value>
      <webElementGuid>c0b4a114-856b-45ab-8b44-53c2e3dafb2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Financial Dashboards'])[1]/preceding::a[1]</value>
      <webElementGuid>89696e23-33a5-4b62-b4c0-40567a03fdf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quiz Results'])[1]/preceding::a[2]</value>
      <webElementGuid>d6088d77-5181-4e6b-a29d-1793a5a41f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Activity Dashboards']/parent::*</value>
      <webElementGuid>b83fe367-9be4-4333-86f9-8b04addbb260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.php?option=com_reports&amp;view=activity_dashboards')]</value>
      <webElementGuid>91086239-e723-499d-9211-b35e1a6f20af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/ul/li[4]/a</value>
      <webElementGuid>4cdd9cf0-e0f8-4798-8183-f2edc3208592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'index.php?option=com_reports&amp;view=activity_dashboards' and (text() = '
                                        Activity Dashboards                                                                                                                    ' or . = '
                                        Activity Dashboards                                                                                                                    ')]</value>
      <webElementGuid>e78fef87-0c7e-4d44-8b48-b9aba53dabed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
